### ISSUE TITLE
Publish 0.7.1

### ISSUE THREAD

**Issue by ynnadrules** [readdle/swift-java-codegen#22]
@andriydruk / @zayass 

Would it be possible to get the latest changes in master that fix Swift 5 warnings for generated code published?

Thanks!

**Comment by zayass** [comment]
Where did you see 0.7.1?
As I know 0.7.0 latest version and it is published
Warnings also should be fixed in 0.7.0

**Comment by ynnadrules** [comment]
Sorry, I meant that a version 0.7.1 should be published with the latest changes in master. But yeah I just realized the changes in 0.7.1 were for the sample project. So never mind. Thanks @zayass
